# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='category')),
                ('category_slug', models.SlugField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_description', models.TextField()),
                ('product_slug', models.SlugField(default=1, max_length=200)),
                ('product_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=200)),
                ('subcategory_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='productnew',
            name='product_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.Subcategory', verbose_name='Subcategories'),
        ),
    ]
